Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda3/envs/lecture-python/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ifp = IFP()

# Set up initial consumption policy of consuming all assets at all z
z_size = len(ifp.P)
a_grid = ifp.asset_grid
a_size = len(a_grid)
Ïƒ_init = np.repeat(a_grid.reshape(a_size, 1), z_size, axis=1)

Ïƒ_star = solve_model_time_iter(ifp, Ïƒ_init)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-6-b7939a5d9206>[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0mÏƒ_init[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mrepeat[0m[0;34m([0m[0ma_grid[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0ma_size[0m[0;34m,[0m [0;36m1[0m[0;34m)[0m[0;34m,[0m [0mz_size[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;34m[0m[0m
[0;32m----> 9[0;31m [0mÏƒ_star[0m [0;34m=[0m [0msolve_model_time_iter[0m[0;34m([0m[0mifp[0m[0;34m,[0m [0mÏƒ_init[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'solve_model_time_iter' is not defined
NameError: name 'solve_model_time_iter' is not defined

